"""add Department

Revision ID: 39389ebc8134
Revises: ee71efb5e5e5
Create Date: 2024-07-07 00:57:24.788921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39389ebc8134'
down_revision = 'ee71efb5e5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
