"""rename column

Revision ID: 562b0d26ed59
Revises: cb473b0d1c3d
Create Date: 2024-07-07 11:00:41.170136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562b0d26ed59'
down_revision = 'cb473b0d1c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.String(length=200), nullable=True))
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(length=200), nullable=True))
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
