"""rename department

Revision ID: cb473b0d1c3d
Revises: 39389ebc8134
Create Date: 2024-07-07 10:40:01.370902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb473b0d1c3d'
down_revision = '39389ebc8134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('departments',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('address', sa.String(length=200), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('department',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    # sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
